sudo: required
services:
    - docker

before_install:
    - docker build -t kamini/docker-react -f Dockerfile .

script:
    - docker run kamini/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "ap-southeast-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-ap-southeast-2-87183992803"
    bucket_path: "docker"
    on:
       branch: master
    access_key_id:  "$AWS_ACCESS_KEY"
    secret_access_key:
        secure: "$AWS_SECRET_KEY"


